### PR TITLE
refactor: remove Game singleton usage in a lot of places

### PR DESCRIPTION
**Pull request by yoda-jm**
PTAL, this is open for discussion, the few places where the singleton is still there:
- audio.cc: this is really hacky and we should never have to look for screens there
- texture.cc: here we want to access the shader cache that lies in Window object
- video_driver.cc: we need to access the Window in order to do updates there (shader ?) : Colors and transformations

Tell me what you think of this. I think that removing the singleton will help because:
- it will be clear where the game is used (and why)
- it will make it dirty to have the Game object floating everywhere, increasing insentive to clear the code
- Singleton pattern is not nice (time span of the object is unknown, problem on destruction, ...

Yet, we can add a "singletong" to Window maybe (making it non-copyable and having a atomic static boolean preventing from creating it multiple times).

### CODE REVIEW

**Comment by OznOg** [comment]
Singleton are evil, and like doing drug, you feel it helpful until you die from them.
Let's merge that

**Comment by Baklap4** [comment]
Looks like a nice refactor. Still gotta test it though

**Comment by Baklap4** [comment]
@yoda-jm can you resolve the conflict within `game/screen.hh` some classes have been moved/restructed in #575

**Comment by yoda-jm** [comment]
> @yoda-jm can you resolve the conflict within `game/screen.hh` some classes have been moved/restructed in #575

done

**Comment by Lord-Kamina** [comment]
Essentially, the idea is to keep references to the actual subsystems we need where we need them?

Haven't tested it (hadn't seen this PR earlier) but looks good.

**Comment by Baklap4** [comment]
While testing i did encounter one error, but couldn't recreate it.
I got a bunch of violationexceptions within `C:\Users\Arjan\source\repos\performous\vcpkg\buildtrees\libepoxy\x64-windows-dbg\src\gl_generated_dispatch.c` on exit. Not sure if that's the cause of this pr though.

**Comment by twollgam** [comment]
@yoda-jm is it OK if I take this PR. If I can I would try to update it and finally to merge it.

**Comment by twollgam** [comment]
I chatted with yoda-jm. It is ok that I try to update and merge the pr/branch.

**Comment by twollgam** [comment]
@yoda-jm , @Baklap4 , @Lord-Kamina this PR can be closed IMHO, cause I used yodas changes in #832 and that one is merged. OK?

**Comment by twollgam** [comment]
I close the pull request cause it is a subset of #832 which is already merged.

**Pull request closed without merging**
