### PR TITLE
Fix keyboard instrument/nav keys getting stuck if released while holding mod keys

### LINKED ISSUE #232: Keypressed Loop
While sorting out songs i came acros this 'bug'

# Act
Within the song browser i'm holding the Right arrow. Then i press ctrl + R 

# Thought it'd do
Reload the whole song library.

# It does the following
- Reloads the song library and keeps on browsing songs to the right, which heavenly speeds up the animation.

# To stop the loop
- Press the same arrow key and quickly press the oposite arrow key.

### PR DESCRIPTION
**Pull request by Tronic**
Fix #232

### CODE REVIEW

**Comment by Baklap4** [comment]
will test this out later this week! Thanks for the pr 👍

**Review by Baklap4 — CHANGES_REQUESTED** [review]
LGTM but i'd use the private member instead of the created variable for the rest of the method. If we're not using the member variable than we should remove the `m_mod = mod` line

The bug is fixed with this :)

**Review by Baklap4 — APPROVED** [review]
LGTM @ooshlablu is still testing though let's await that and then merge it :)

**Comment by ooshlablu** [comment]
I can confirm this fix works on Ubuntu 18.04 and 20.04.

**Comment by Baklap4** [comment]
Thanks for the fix @Tronic 👍

**Pull request merged**
