### PR TITLE
Fix macOS cache on semaphore build

### PR DESCRIPTION
**Pull request by Lord-Kamina**
### More

- [ ] Added/updated documentation

### CODE REVIEW

**Comment by Baklap4** [comment]
I think this is still a draft branch? (since it failed after it hit the 15 minute timer)

**Comment by Lord-Kamina** [comment]
> I think this is still a draft branch? (since it failed after it hit the 15 minute timer)

Yeah, it took me quite a while because I had missed something. I think we're good now; though.

**Comment by Baklap4** [comment]
I'm currently rerunning the pipeline for a few times. As of your initial it came down to 4 minutes for osx build which is nice!

**Review by Baklap4 — APPROVED** [review]
LGTM ci pipeline is about 4 minutes for osx which is pretty good compared to 15+ minutes. Let's see if it holds up during other PR's.

**Pull request merged**
