### PR TITLE
Remove boost variant

### PR DESCRIPTION
**Pull request by OznOg**
<!--

### What does this PR do?

Remove use of boost variant, replace by std::variant

### Closes Issue(s)

part of task #39

### CODE REVIEW

**Review by Baklap4 — APPROVED** [review]
LGTM

**Comment by OznOg** [comment]
Any help on what is making the buid fail is welcome....

**Comment by Baklap4** [comment]
> Any help on what is making the buid fail is welcome....

Seems it was just a timeout issue. Reran the bild and it worked 🤷 

@Lord-Kamina can we improve the speed of the mac builds?

**Comment by Lord-Kamina** [comment]
> > Any help on what is making the buid fail is welcome....
> 
> Seems it was just a timeout issue. Reran the bild and it worked 🤷
> 
> @Lord-Kamina can we improve the speed of the mac builds?

Not without the cache feature.

**Pull request merged**
