### PR TITLE
[WIP] Bug fix/audio crackles

### LINKED ISSUE #327: Loud pops when starting/restarting audio.
I don't know if anybody else has noticed this?

Sometimes when the audio starts or is destroyed, it makes a really loud pop... I was wondering whether it might be possible to fix this?

### PR DESCRIPTION
**Pull request by Lord-Kamina**
First and foremost, I mostly classified this as WIP not because it actually is WIP but rather because I'm somewhat throwing punches in the dark and seeing if I hit something here. And, I think I might have.

I was taking a look at #327... I discarded ffmpeg as possible culprit by commenting out all the actual calls to play music and/or samples, confirming the noises were still there. This had to mean the issue was in the initialization of the audio subsystem, most likely something to do with portaudio.

Then, I got this idea and at least for me, it seems to get rid of the issue. Could other people please confirm?

# Issues
* Closes #327

### CODE REVIEW

**Comment by Tronic** [comment]
Could you add comments to the code because it is not clear why a delay and such initialization order are necessary?

**Comment by Lord-Kamina** [comment]
@Tronic, I basically kept the same order it was being done in before, with the added delay. The reason for the delay? Honestly I have no idea, it was just something I tried and for some reason it seems to reliably get rid of the issue for me, which is why I wanted input from the rest of you.

@yoda-jm suggested in Discord " I have the feeling that the problem was just that we did not initialize the output buffer before starting p" but honestly I'm not sure how to do that. I'm certainly open to less-hacky solutions if anybody has them.

**Comment by Tronic** [comment]
@Lord-Kamina Can you see if #359 fixes this issue or if the delay or other changes are also needed?

**Comment by Lord-Kamina** [comment]
Can I get back to you on this in a couple weeks? Currently computerless.

**Comment by Baklap4** [comment]
Marked as on hold because it might be fixed in #359

**Comment by Lord-Kamina** [comment]
This is still an issue with latest master, not fixed by #359 D:

**Comment by Baklap4** [comment]
There are some merge conflicts here

**Comment by Lord-Kamina** [comment]
Theoretically this is superceded by #384

**Pull request closed without merging**
