### PR TITLE
Fix fs with boost 1 74

### PR DESCRIPTION
**Pull request by OznOg**
Fix compilation when using boost FS >= 1.74

### CODE REVIEW

**Review by Baklap4 — APPROVED** [review]
LGTM

**Comment by Lord-Kamina** [comment]
@Tronic could you check whether this fixes the error you found previously with `performous_app_build.sh`?

**Comment by OznOg** [comment]
I'm affraid, there is something wrong still; Just figured out that create_directory has inverted parameter with copy_directory, thus the code may be wrong as I would need to invert :
`                        else { create_directory(path, destinationDir / relativePathStr); }` in fc.cpp
I'll need to make some more checks,..
@Tronic You may check compilation anyway, as you problem is plain compilation pb AFAII
@Baklap4 please wait for my check to complete before merging

**Review by Baklap4 — APPROVED** [review]
Confirmed by other mac user (@ooshlablu) that this resolves this building issue.

**Comment by Baklap4** [comment]
@OznOg rebase and merge when you're up for it :+1:

**Pull request merged**
