### PR TITLE
add new theme PERFORMOUS+

### PR DESCRIPTION
**Pull request by marwin89**
### What does this PR do?

- add a totally new theme "performous+" (new bgm, style, fonts, icons, backgrounds, notes, guitarneck, skin, layouts etc.)
- 2 skins: color/black
- add new backgrounds
- add new font family "FreeSans"
- Everything in this theme (incl. bgm and logo-font) is free for commercial use (most based on pixabay content, only webfontsonline need a little attribution see "copyright"-folder).
- All copy right information are included in "copyright"-folder.

### Closes Issue(s)

- x

### Motivation

- total re-design
- broaden the audience for this game
- new standard-theme besides default, default-green
- motivate you to improve theming feature
- motivate designers
- new basis for upcoming themes

### More

Color
performous+ mainscreen-color
performous+ singscreen-color
performous+ songlist-color2
performous+ songscreen-color
performous+ guitarscreen

Black
performous+ songscreen

### Additional Notes

- This theme is made with Inkscape (0.92.4). I'll saved all SVG as Inkscape-SVG.

- There is also an [avatar collection](https://github.com/marwin89/Vocaluxe-Ultrastar-Profile-Add-On) I made for ultrastar games, melody mania and vocaluxe: Maybe you can link to it anyhow. It's for performous too and has over 80 pictures. Hopefully this motivates you to improve avatar-feature for players.

### CODE REVIEW

**Comment by Baklap4** [comment]
Accepted the runner to run, results are above 👍 gonna check it out somewhere later this week :D

**Comment by Baklap4** [comment]
I just took a quick look through the changed files. @marwin89 can you check what happens if you delete the www folder? Does it fallback to the default theme folder? If yes, i'd prefer that over duplicating the sources

**Comment by marwin89** [comment]
it works fine without www-folder duplicate. 
removed it in 2nd commit, improved backgrounds for settings and test.

**Comment by Baklap4** [comment]
@marwin89 if you'd want to style the webserver-ui a list of endpoints can be found here: https://github.com/performous/performous/wiki/Webserver-API

With the use of these endpoints any frontend website can be made :)


Also i'm wondering what issues you were and are facing whilst coming up with this beautiful theme
We do have a couple of theme related issues: #876 #723 #563 #564 #560 #47

**Comment by marwin89** [comment]
> Also i'm wondering what issues you were and are facing whilst coming up with this beautiful theme
> We do have a couple of theme related issues: https://github.com/performous/performous/issues/876 https://github.com/performous/performous/issues/723 https://github.com/performous/performous/issues/563 https://github.com/performous/performous/issues/564 https://github.com/performous/performous/issues/560 https://github.com/performous/performous/issues/47

I will look into it.

Updated screenshots above and mentioned avatar collection.

**Comment by ooshlablu** [comment]
I just did a few tests with the deb and Appimage on Ubuntu 20.04, and I seem to be hitting some sort of weird crash where some of the elements become unavailable or something. For instance, the button markers on the fret board start off as black in the center as they should, but then they are filled with white, and look very pixel-y almost. I have noticed also that the stars that show up when a player does really well on a vocal section disappear after the guitar buttons get messed up. This happens with both guitar and Bass.
I seriously doubt these issues are a part of the theme itself, and I don't think whatever is causing them was introduced by this PR. Overall the theme looks great, and I definitely would love to have it in Performous.
I'll see if  the same thing happens on Ubuntu 22.04 in a little bit.
Screenshot from 2023-10-06 12-43-20
Screenshot from 2023-10-06 12-49-27

**Comment by Baklap4** [comment]
Hmmm these squares happen when a file cannot be found i think. As for pixeled images might be a result of using pngs/jpegs instead of svg? (Not sure if that applies to this pr though)

**Comment by twollgam** [comment]
> Hmmm i think i do like the colored screenshots more than the black 'n white ones. It popped way more before :)

Where are the color screenshots? I like the b/w ones, so can we have both? (in two themes for example)

**Comment by marwin89** [comment]
I'll upload the colorful screenshots in the next days again. 👋 

BTW Suggestion 💡: It would be very cool if every theme has their own "backgrounds"-folder (maybe "fonts"-folder, "profile-pic"-folder too). Maybe this is technical possible in another pull-req? Cause the backgrounds of default have a complete different style. I guess the backgrounds should be selected by the theme designer. Is there any argument against this approach?

**Comment by twollgam** [comment]
> BTW Suggestion 💡: It would be very cool if every theme has their own "backgrounds"-folder (maybe "fonts"-folder, "profile-pic"-folder too). Maybe this is technical possible in another pull-req? Cause the backgrounds of default have a complete different style. I guess the backgrounds should be selected by the theme designer. What do you think?

Please look if there is already an issue or make a new one with your ideas. So we could discuss what and how we can implement new features.

**Comment by marwin89** [comment]
### New commit # 5: 
More fixes and updates

- Add black theme and color theme
- changed practice.ogg
- font fixes etc.
- re-added (default-backgrounds svgs)

**Comment by Baklap4** [comment]
Re-running the appimage job since it got a 403... this shouldn't happen :) 

In regard to the white squares... we might need to look into that before getting this to merge... gotta see if we can reproduce it @ooshlablu

**Comment by marwin89** [comment]
New commit # 6:

More fixes and updates

- re-added note lines in practice background

**Comment by twollgam** [comment]
@marwin89 what is the current state of this pr? How far from merging is it?

**Comment by ooshlablu** [comment]
I just tested again, and the white boxes that appeared over/replaced the star when you do well in a section seem to have gone away. The star appears as you would expect.
The white still pops up for the instruments though. I still am not sure what could be causing that.

**Comment by marwin89** [comment]
> what is the current state of this pr? How far from merging is it?

1. @twollgam, from my view its done (for this iteration). 😄 Yet as @ooshlablu wrote that there is 1 (maybe technical) error to check. If thats checked, we can merge 🎉 
2. Info for all: I'll update performous+ theme once a year (end of year) along side with avatar collection #928 
3. Ask me any time for support/advice when devs layout new features 👍

**Comment by Baklap4** [comment]
> 3. Ask me any time for support/advice when devs layout new features 👍

@marwin89 i think this pr doesn't come with an update to the webserver-ui. For now that's fine but it'd be nice to add this to the theme aswell (could be introduced in another pr) 👍 

As for the white squares on the instruments i think we need more details. @ooshlablu can you create an issue for this? Then we can merge this pr :)

**Comment by ooshlablu** [comment]
Yeah, this is ok to merge. I tested with the default theme with these packages also, and I didn't see any issues there. I meant to mention that in my last comment :-)

**Pull request merged**
