### PR TITLE
Added osx build

### PR DESCRIPTION
**Pull request by Baklap4**
### What does this PR do?

Adds a clang semaphore build fox Mac OSX.

### Partly fixes Issue(s)

#389 

### Motivation

Automate whatever you can especially a build street.

### CODE REVIEW

**Comment by Baklap4** [comment]
@Lord-Kamina i'm about to get this merged to master.
If you eventually get the cache on your branch working feel free to add a new pr :)

**Comment by Baklap4** [comment]
@nieknooijens tagged you as a reviewer since both @Lord-Kamina and i worked on this

**Comment by Lord-Kamina** [comment]
I'm still trying my alternative approach. Will approve this once I've concluded and if it really proves worse than your solution

**Comment by Baklap4** [comment]
@Lord-Kamina as for now the build times i've seen are around 10-15 minutes.
With my trial and error the last time only getting 1.3GB's from semaphore cache alone took around 5 minutes, let be installing performous. The build within this PR are at 5-6 minutes to complete all 3 environments..

Since we're still in quite an optimizing phase of our CI (adding osx builds, hopefully soon windows builds) I think it's alright to just create a pr for the caching mechanic since that'd be an improvement.

I'm also wanting to look at github's implementation of a CI since they do have windows machines available and i have no clue when semaphore is going to support them: https://github.com/semaphoreci/docs/issues/741

**Comment by Lord-Kamina** [comment]
> @Lord-Kamina as for now the build times i've seen (on the cache branch) are around 10-15 minutes.
> With my trial and error the last time only getting 1.3GB's from semaphore cache alone took around 5 minutes, let be building / installing performous. The build within this PR are at 5-6 minutes to complete all 3 environments..
> 
> Since we're still in quite an optimizing phase of our CI (adding osx builds, hopefully soon windows builds) I think it's alright to just create a pr for the caching mechanic since that'd be an improvement.
> 
> I'm also wanting to look at github's implementation of a CI since they do have windows machines available and i have no clue when semaphore is going to support them: [semaphoreci/docs#741](https://github.com/semaphoreci/docs/issues/741)

Yeah, I haven't had the time to finish implementing the cache version yet. Will report back when I do.

**Comment by Baklap4** [comment]
Closing in favor of #527

**Pull request closed without merging**
