### PR TITLE
Playlist duration

### PR DESCRIPTION
**Pull request by nieknooijens**
this branch allows you to view how long it takes until song X arrives as described in #182 
The only way to get the duration of an audio file is to completely read it, this puts stress on the filesystem so to make sure we access the filesystem as little as possible I designed it in the following way:
when screenPlaylist comes up (main thread) or the playlist is requested from the web frontend (webserver thread) they call getDurationSeconds() on the song object. this function checks whether the duration is already known and if so, it returns it, if not it opens up ffmpeg and decodes the music file, calculates the duration and stores it in memmory so it doesn't have to be read from disk again when the duration is requested next time.
this way we put as little stress on the system as possible, only fully loading the songs that are actually put in the playlist and only loading them once.

### CODE REVIEW

**Comment by Baklap4** [comment]
I've checked the enhancements you did make, it looks great!
A few things to make it look even better would be:

- Time in the format: hh:mm:ss (when an hour is reached. Else mm:ss)
- The next one in line currently shows 00:00 min. It'd be great to see this being the length of the current song being played counting down towards 00:00 min. Which also brings me to the 3rd point
- Counting down the time while the current song is playing.

The 3rd point: 
As the webserver view (within the browser) does can be set to refresh every 10 secs it would be nice to update the time aswell.

**Comment by TobiX** [comment]
Congratulation, you mixed rebase and merge, now every commit is doubled.

**Comment by nieknooijens** [comment]
@TobiX ok, well at least I went through the trouble of rebasing it.

**Comment by TobiX** [comment]
Well, that obviously isn't useful if you then merge the old and new branches. Anyways, just ignore my bickering, I'll probably won't contribute much anymore, since I stopped using Performous almost a year ago.

**Comment by nieknooijens** [comment]
@TobiX hey I'm still student for at least 6 months so I can still say I'm learning! (most of my classmates have never used git before... so me screwing up once in a while isn't that bad)

**Pull request merged**
