### PR TITLE
fix: cleanup ffmpeg warnings

### LINKED ISSUE #229: resolve FFMPEG depricated calls
yes they did it again! the following stuff has been deprecated this time:
avframe::pkt_pts
avcodec_decode_video2()
avcodec_decode_audio4()
avstream::codec

### PR DESCRIPTION
**Pull request by yoda-jm**
The code is now compliant with latest ffmpeg API.

# Issues related
* Closes #229

### CODE REVIEW

**Comment by nieknooijens** [comment]
is this a continuation of my fix-warnings branch? because I worked on that as well, it just needed some cleanup.

**Comment by yoda-jm** [comment]
I've only seen your fix-warnings branch after. I tries to focus on using what seems to be the good practice for developping with ffmpeg. Especially the way to initialize the decoder and the frame decoding double loop.
This code is working, I only once got a segfault in the audio playback, I don't know if it is related to this patch (maybe an empty audio buffer was sent).

**Comment by nieknooijens** [comment]
ok lemme check this through 1 more time then it's ok to merge. I closed my PR, since it did the same thing but messier.

**Comment by nieknooijens** [comment]
got a crash:

```
Thread 11 "performous" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc485f700 (LWP 12559)]
RingBuffer<2048ul>::insert<da::step_iterator<float const> > (begin=..., 
    this=0x55555596e2c8 <vtable for boost::detail::sp_counted_impl_p<boost::detail::thread_data<boost::_bi::bind_t<void, int (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > >+24>, end=...)
    at /home/niek/Projects/performous/game/pitch.hh:45
45				m_buf[w] = *begin++;  // Copy sample
(gdb) bt
#0  0x00005555555e0e73 in RingBuffer<2048ul>::insert<da::step_iterator<float const> >(da::step_iterator<float const>, da::step_iterator<float const>) (begin=..., this=0x55555596e2c8 <vtable for boost::detail::sp_counted_impl_p<boost::detail::thread_data<boost::_bi::bind_t<void, int (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > >+24>, end=...)
    at /home/niek/Projects/performous/game/pitch.hh:45
#1  0x00005555555e0e73 in Analyzer::input<da::step_iterator<float const> >(da::step_iterator<float const>, da::step_iterator<float const>) (begin=..., this=0x55555596e2c0 <vtable for boost::detail::sp_counted_impl_p<boost::detail::thread_data<boost::_bi::bind_t<void, int (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > >+16>, end=...) at /home/niek/Projects/performous/game/pitch.hh:80
#2  0x00005555555e0e73 in Device::operator()(void const*, void*, unsigned long, PaStreamCallbackTimeInfo const*, unsigned long) (this=0x555555b064c0, input=<optimized out>, output=0x0, frames=900)
    at /home/niek/Projects/performous/game/audio.cc:417
#3  0x00007ffff21c08b4 in  () at /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#4  0x00007ffff21c28c4 in  () at /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#5  0x00007ffff21cb7cc in  () at /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#6  0x00007ffff6d097fc in start_thread (arg=0x7fffc485f700)
    at pthread_create.c:465
#7  0x00007ffff091ab5f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

I merged our latest master with your changes so unfortunately I cannot approve this. yet
system:
ubuntu 17.10
tested on both intel HD4000 and nvidia GT840M
RAM 16GB DDR3
cpu intel i7 4710MQ

**Comment by yoda-jm** [comment]
If you have a reproducer could you check if after decoding we sent an empty/nil/whatever audio buffer (tests in processAudio might be missing like the alloc return, the input size or the out_samples (haven't been able to have a reproducer on this one).

**Comment by Baklap4** [comment]
Running latest master with this branch (with libxml++3.0 installed) i'm facing no errors.
Looks good to me :+1:

**Comment by yoda-jm** [comment]
Hello, with 2 preliminary patch that avoids dying

**Pull request merged**
