### PR TITLE
Fixed the 4px side scrolling bug on the web interface

### PR DESCRIPTION
**Pull request by skyli91**
and made the code look a bit better (css)
also left aligned the headers of the database view table

### CODE REVIEW

**Comment by nieknooijens** [comment]
schermafdruk van 2016-06-17 15-03-24

hmmm.... I don't like that gap on the right.

**Comment by skyli91** [comment]
that was there before too but yeah it's a bug, let me see if i can fix :)

**Comment by skyli91** [comment]
check now :)

**Comment by nieknooijens** [comment]
yup that's perfect. thanks!
BTW: I'm a bit busy at work, got a few deadlines, so I'll not be programming for another 8 days, only accepting pull requests.
after that I'll try to get rid of some open issues.

**Pull request merged**
