### PR TITLE
Meson build checker

### PR DESCRIPTION
**Pull request by Baklap4**
Used to keep on checking the meson build. Can be ignored for most devs.

### CODE REVIEW

**Comment by deuteragenie** [comment]
Nice !

**Comment by Baklap4** [comment]
Build is broken due to missing PPA from @Lord-Kamina

**Comment by Lord-Kamina** [comment]
> Build is broken due to missing PPA from @Lord-Kamina 

Should be fixed if you mefrge master.

**Comment by Baklap4** [comment]
> Should be fixed if you merge master.

I already did that ;P Meson build lacks the line: add-ppa
I'll make a pr for it sometime later

**Comment by Baklap4** [comment]
Build is fixed again :)

**Comment by Baklap4** [comment]
Closing PR since we don't have semaphore CI anymore.

**Pull request closed without merging**
