### PR TITLE
Remove extraneous semicolons

### PR DESCRIPTION
**Pull request by deuteragenie**
Remove extraneous semicolons.

Note: This PR addresses all pedantic warnings left over with the compilation option specific in the experimental meson build.

Outstanding warnings from GCC after this is applied:

```
[16/71] Compiling C++ object performous.p/game_glshader.cc.o
../game/glshader.cc: In member function ‘void Shader::dumpInfoLog(GLuint)’:
../game/glshader.cc:34:7: warning: ISO C++ forbids variable length array ‘infoLog’ [-Wvla]
   34 |  char infoLog[maxLength];
      |       ^~~~~~~
[23/71] Compiling C++ object performous.p/game_controllers.cc.o
../game/controllers.cc: In constructor ‘ButtonMap::ButtonMap()’:
../game/controllers.cc:92:50: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct ButtonMap’; use assignment or value-initialization instead [-Wclass-memaccess]
   92 |  ButtonMap() { std::memset(this, 0, sizeof(*this)); }
      |                                                  ^
../game/controllers.cc:88:8: note: ‘struct ButtonMap’ declared here
   88 | struct ButtonMap {

### CODE REVIEW

**Review by OznOg — COMMENTED** [review]
LGTM

**Review by Baklap4 — APPROVED** [review]
LGTM

**Comment by Tronic** [comment]
> Outstanding warnings from GCC after this is applied:
> 
> ```
> [16/71] Compiling C++ object performous.p/game_glshader.cc.o
> ../game/glshader.cc: In member function ‘void Shader::dumpInfoLog(GLuint)’:
> ../game/glshader.cc:34:7: warning: ISO C++ forbids variable length array ‘infoLog’ [-Wvla]
>    34 |  char infoLog[maxLength];
>       |       ^~~~~~~
> ```

It should be easy to fix this too
```c++
std::vector<char> infoLog(maxLength); /* and where needed */ infolog.data()
```

**Comment by deuteragenie** [comment]
Thank you !

**Pull request merged**
