### PR TITLE
Fix races on m_songs in Songs

### PR DESCRIPTION
**Pull request by OznOg**
The m_songs member was not locked correctly.

This was leading to random crashes while loading many songs and/or while applying filters while loading many songs.

### CODE REVIEW

**Comment by Baklap4** [comment]
YES FINALLY! i had this sometimes, but never could really get a lead on to where it happened

**Comment by Baklap4** [comment]
Is there any way to actually test this properly?
As to me it happened mostly at random times :/

**Comment by OznOg** [comment]
> Is there any way to actually test this properly? As to me it happened mostly at random times :/
> 
> Maybe, if possible, add a unittest for this since with regular play it's hard to actually reproduce it

Like any race, I can be quite hard to do on purpose. You may add some sleeps on the code when loading the cache to make the race more "likely". Creating the race itself can be done with some breakpoints on gdb.

**Review by Baklap4 — DISMISSED** [review]
LGTM

**Comment by OznOg** [comment]
I'm affraid there's still something wrong with the filter restore..... Do not merge for now....

**Comment by OznOg** [comment]
> I'm affraid there's still something wrong with the filter restore..... Do not merge for now....

well actually not, the Restore works only on filtered not songs directly.

**Review by Baklap4 — APPROVED** [review]
I can't un-dismiss hahah so LGMT

**Pull request merged**
