### PR TITLE
Webserver (since github refuses to add my later changes)

### PR DESCRIPTION
**Pull request by nieknooijens**
Webserver access is now stable and it even works on windows:
https://www.dropbox.com/s/2b9budw2qx5j4ga/performous-webserver.zip?dl=0
it's optional in the cmake config (-DENABLE_WEBSERVER) and disabled by default so semaphore should be able to build it without problem.

### CODE REVIEW

**Comment by TobiX** [comment]
Would you mind cleaning up that branch (remove *.orig files, remove stuff that's not part of the webserver feature, etc.), maybe even with a rebase? Before that I'm not willing to review this huge change and leave others the honour to merging it.

**Comment by TobiX** [comment]
Oh, I saw you were generating JSON. Are you using a library for that?

**Comment by nieknooijens** [comment]
@TobiX I use a regular string stream to generate Jason since we already have too many libraries and the webserver adds another one. Because cpp-netlib needs additional steps to set up I made it optional.
Everything is described here: https://github.com/performous/performous/wiki/Webserver-support
I even managed to cross-compile it for windows, problems with mxe mwas the main reason this wasn't merged to master 8 months ago.here is the build: https://www.dropbox.com/s/2b9budw2qx5j4ga/performous-webserver.zip?dl=0

**Comment by TobiX** [comment]
IMHO, NIH is much worse then another dependency. OTOH, it seems Boost has a simple JSON parser/generator, so it would by appropriate to use it: http://www.boost.org/doc/libs/1_41_0/doc/html/boost_propertytree/parsers.html#boost_propertytree.parsers.json_parser - My other issues with this branch still stand, though.

**Comment by nieknooijens** [comment]
that would be basically the same, but in stead of using a stringstream, you create a boost property tree (http://www.boost.org/doc/libs/1_41_0/doc/html/boost_propertytree/accessing.html) and then add properties (title, artist, edition etc. etc.) then convert that to json. it's basically the same amount of code. right now I have a stream in which I store all that properties and I manually insert all the JSON  control characters.
I can rewrite it if it's really necessary but I don't think i'll end up with any cleaner code.

**Comment by nieknooijens** [comment]
I used the boost ptree to generate json in the latest commit, but this has serious problems with UTF-8 support. solution would be using the wptree but that has all conversion issues and stuff. I'd like to discuss how we tackle this before I put more time in this.

**Comment by Baklap4** [comment]
When i close performous (with webserver on) and restart it. It has issues binding to the socket as the terminal says: 

webserver/notice: Starting public server.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >'
  what():  Error binding to socket.

Stacktrace: http://pastebin.com/fcsZ8495

-----------------------------------------------------

And i've encountered a segmentation error by drawing the covers
Stacktrace: http://pastebin.com/Z40gUfsk

-----------------------------------------------------

Furthermore when the application is loading songs (threaded) and i choose a song which will be loaded but ain't loaded yet it crashes with an segmentation fault.

**Comment by nieknooijens** [comment]
if you wait for 1 minute it should restart normally (at least on linux)
that should only happen after a crash (since the socket is still in use then)

**Comment by Baklap4** [comment]
That's correct, it happens only on a crash. A bit annoying when you're developing and debuging why your program crashes ;)

**Comment by nieknooijens** [comment]
here's a MXE build of this branch:
https://www.dropbox.com/s/2b9budw2qx5j4ga/performous-webserver.zip?dl=0

**Comment by nieknooijens** [comment]
I'm still stuck with cpp-netlib 0.10 since the ubuntu-package fails to build.

**Comment by nieknooijens** [comment]
yeah, build passed!
https://semaphoreci.com/performous/performous/branches/webserver

**Comment by Baklap4** [comment]
Any idea when this branch will be merged with master? Would be nice to include in the next release, and it works pretty well for atleast me

**Comment by nieknooijens** [comment]
i'll first try to fix issue #168 this weekend then I'll merge this and I want to continue with the danceoverhaul branch. I abandoned that a while ago when I ran into some issues, but I now have some new Ideas how to solve them. Also I now have more experience with openGL so that'll probably help making sense of the code.

**Comment by TobiX** [comment]
As long as this is a 2-year-old 215 commits heavy monster, you will not get my approval to merge this. The others might want to overrule me, but consider this a strong NO from me. (aka. nothing has changed from my opinion in April)

**Comment by nieknooijens** [comment]
So a rebase and a cleanup?
Im on it!

**Comment by nieknooijens** [comment]
so I rebased it and now it's only 160 commits. I also removed some duplicated code from the webserver

**Comment by TobiX** [comment]
I took a quick look, looks a lot better then before. Thanks for all the hard work. If you don't mind, I'll do another rebase this evening and remove some things that shouldn't be on this branch. (Did you merge the danceoverhaul branch into this? I can see some changes in the dance code...)

**Comment by nieknooijens** [comment]
@TobiX I didn't merge the danceoverhaul branch into this, but while working on the danceoverhaul branch I sometimes acidentally comitted to this one, just remove what's in there!

**Comment by TobiX** [comment]
Reduced to ~106 patches. Reviewing should be a bit easier now. I think I threw out all patches related to the danceoverhaul branch. I'd like to suggest a release (1.1) this weekend and after that merging the webserver branch and then we can see where we go from there. Sounds good? :)

**Comment by nieknooijens** [comment]
sounds great. the "where we go from there" is simple, just view the issues queue!
I wanted to start out with #132 this weekend and I have some new Ideas how to tackle #9 although #9 needs a lot of work! (I wanted to change the SVG's to look like the CEL noteskin from openITG, add rankings etc.)

**Comment by nieknooijens** [comment]
I compiled a windows version using MXE:
https://www.dropbox.com/s/3w2g4u0h658jjb3/Performous-1.2RC1.exe?dl=0

**Comment by nieknooijens** [comment]
I assume we can merge this now? I'll merge it when there's no comment for over a week.

**Comment by TobiX** [comment]
Yeah, I didn't get around to create a release... It would be nice to have a release before merging it... I see if I get around to creating a release over the 32c3...

**Comment by Lord-Kamina** [comment]
This branch is such a mess that I tried to pull the changes to my fork's
webservee branch and it's not mergeable hahaha.

On Friday, 25 December 2015, Tobias Gruetzmacher <notifications@github.com>
wrote:

> Yeah, I didn't get around to create a release... It would be nice to have
> a release before merging it... I see if I get around to creating a release
> over the 32c3...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/pull/145#issuecomment-167265087>
> .
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by nieknooijens** [comment]
@Lord-Kamina it has been rebased on current master to clean up the mess, that's why the merge doesn't work ;-)

**Comment by nieknooijens** [comment]
@TobiX how was 32c3? I viewed some talks online but couldn't be there. Did you manage to push a 1.1 release?

**Comment by nieknooijens** [comment]
since we now released 1.1, I'd like to merge this one.

**Comment by TobiX** [comment]
Please merge if you come around to it. We can discuss further issues on master. (For example I don't like the "webserver is active" sound) We are currently such a small team that IMHO we can't afford to divide our attention to to much diverging branches.

**Pull request merged**
