### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jose1711**
### What does this PR do?

Only fixes a small typo in output log.

### CODE REVIEW

**Comment by Baklap4** [comment]
I have just merged it. I didn't consider it done regarding the open features. I brought these to #389 . Anyway @jose1711 can you rebase your master upon origin then we can merge this fella aswel :+1:

**Comment by Baklap4** [comment]
Please use a rebase instead of a merge commit:
`git checkout master && git pull && git rebase -i origin/master`
This will create a diverged commit (with only your changes) which you'll have to force push to your master branch :+1:

**Comment by jose1711** [comment]
> Please use a rebase instead of a merge commit:
> `git checkout master && git pull && git rebase -i origin/master`
> This will create a diverged commit (with only your changes) which you'll have to force push to your master branch +1

thank you, hope i got it right this time

**Comment by Baklap4** [comment]
@Lord-Kamina i think somehow the semaphore 2.0 builds can't checkout forks of the repo.. o.o'?

**Comment by Baklap4** [comment]
@jose1711 can you rebase your master branch again with the previous command? (we merged your translation already :))

**Pull request merged**
