### PR TITLE
Upgraded CED

### LINKED ISSUE #471: Update CED submodule to latest CED commit
The title says it all.
This will address several warnings issued by the compiler on the current CED sub-module.  These have been addressed upstream.

### PR DESCRIPTION
**Pull request by Baklap4**
### What does this PR do?

Updates ced dependency to the latest of upstream

### Closes Issue(s)

Closes #471 

### Motivation

Digging through old issues and wanting to close them.

### CODE REVIEW

**Comment by Lord-Kamina** [comment]
Uhhhh I think I'd done this in another PR maybe?

**Comment by Lord-Kamina** [comment]
Upstream always had the unit tests; I removed them on purpose because it's more dependencies and because they possibly depend on downloading a file during the build, which is kind of a no-no in many environments.

**Comment by Baklap4** [comment]
Yeah i see that now, removing it again

**Comment by Baklap4** [comment]
Build should be working now

**Comment by Lord-Kamina** [comment]
There's an issue with the submodule ref

**Comment by Lord-Kamina** [comment]
ced head on our end is `c5c9558`, while submodule ref is `630e5b`

**Comment by Baklap4** [comment]
Fixed the head, i had some weird issue regarding 'author' in git commit..

**Pull request merged**
