### PR TITLE
Webserver

### PR DESCRIPTION
**Pull request by nieknooijens**
implemented a webserver and remote page to control the playlist.
by default the webserver is disabled, you can enable it in the configuration-menu, you can configure if the server should be local-only or all-connections and you can change the port on which it's served.

this curently breaks the windows-build, also I improved it after this request so those changes should be pulled too.

### CODE REVIEW

**Comment by nieknooijens** [comment]
I made a windows build of the webserver:
https://www.dropbox.com/s/2b9budw2qx5j4ga/performous-webserver.zip?dl=0

**Comment by Baklap4** [comment]
Working over here @windows @ubuntu :+1:

**Comment by Lord-Kamina** [comment]
Care to give me a primer on how to use this so I can test it later on mac?

On Sunday, April 26, 2015, niek nooijens <notifications@github.com> wrote:

> Closed #60 <https://github.com/performous/performous/pull/60>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/pull/60#event-290268236>.
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png]  Interno de
Medicina  Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by nieknooijens** [comment]
Clone this https://github.com/cpp-netlib/cpp-netlib/tree/0.10-devel

And move the boost folder to your include folder.
So you should have include/boost/network/protocol/http/server.hpp
Then enable it in cmake by passing -DENABLE_WEBSERVER or check the checkbox in cmake-gui.
Then it should build normally.

The webserver is described in the wiki: https://github.com/performous/performous/wiki/Webserver-support

**Pull request closed without merging**
