### PR TITLE
Include specific header for opencv

### PR DESCRIPTION
**Pull request by deuteragenie**
For webcam support, include the specific header required (ie <opencv2/videoio.hpp>
) rather than the generic one (ie #include <opencv2/opencv.hpp>)

This results in faster parse time.

When installing dependencies, we can probably only install opencv-videoio, which has a smaller footprint than the generic opencv and depends on opencv-core which is also required.

Tested on Ubuntu 21.04.

### CODE REVIEW

**Comment by Baklap4** [comment]
> When installing dependencies, we can probably only install opencv-videoio, which has a smaller footprint than the generic opencv and depends on opencv-core which is also required.

Can you add the install of the specific library to this pr?

**Review by Baklap4 — APPROVED** [review]
LGTM

**Comment by Baklap4** [comment]
@deuteragenie This PR broke the meson build

**Comment by deuteragenie** [comment]
Let us wait until the OSX PR is merged first.

**Pull request merged**
