### PR TITLE
Fix submodule paths.

### PR DESCRIPTION
**Pull request by Lord-Kamina**
This should fix the issues with submodules on forks.

### More

- [ ] Added/updated documentation

### CODE REVIEW

**Review by Baklap4 — APPROVED** [review]
LGTM

**Comment by OznOg** [comment]
I'm a bit late, but as far as I remember, ../ were added on purpose to allow testing modification in submodules, I'm affraid we get back in a previous bug...

**Comment by Baklap4** [comment]
I think you're right @OznOg 
Hmmm the changes `../` were added as part of #501 

The problem what is being fixed here is people who forked the repo and didn't fork the submodules couldn't build.

Now both parties can build and soon (#595) submodules won't be a thing anymore
The ones who checked out using ssh will have to provide a username/password for the submodule to clone though

**Comment by OznOg** [comment]
you are right, let's see with #595

**Comment by deuteragenie** [comment]
Yes, let us see how it goes with aubio from system pkgs and ced from repo.  
On the test meson builds, it already works without any need for submodules.

**Pull request merged**
