### PR TITLE
Feature/fix warnings

### PR DESCRIPTION
**Pull request by nieknooijens**
fixed compile warnings, mostly case fall through ones (which require a comment to let the compiler know it was on purpose) and some ffmpeg stuff (they actually made the API easier to understand, but forgot to document it as always). there are still some std-auto-ptr deprecated errors, but these come from boost which is not our buisness. boost should fix those.

### CODE REVIEW

**Comment by nieknooijens** [comment]
build failed because semaphore uses ubuntu 14.04 which doesn't have the new ffmpeg API yet

**Comment by nieknooijens** [comment]
@Baklap4 could be possible through PPA, but otherwise I could add in some macro-clutter that determines the ffmpeg version and changes the algorithm accordingly (as we have done in the past way too many times!)

**Comment by Baklap4** [comment]
@nieknooijens i've updated the warnings i've seen just by recompiling. That's all :)

As for the ci, i'd add ifdefs if there's no other solution so we can still support a base 14.04 ubuntu although it's pretty old. Maybe extract those parts to different classes and load the correct class on runtime

**Comment by nieknooijens** [comment]
@Baklap4 I'm not very fond of building in a full strategy-pattern, but i'm not a fan of macro clutter either...

**Comment by Baklap4** [comment]
Strategy pattern's aint that bad imho better than ifdefs :joy: but yeah requires some more but once setup you can just hotplug another version basicly

**Comment by Lord-Kamina** [comment]
I'd do it the same way as I did the platforms. I.e. Common headers, separate implementation.

**Comment by nieknooijens** [comment]
@Baklap4 strategy pattern using preprocessor-macro's is a pain... (you need to use macro's since you don't want deprecated code to be compiled in to avoid errors)

**Comment by nieknooijens** [comment]
#todo: move implementations to their own headers and preprocessor-macro the hell out of it...

**Comment by nieknooijens** [comment]
replaced by #321

**Pull request closed without merging**
