### PR TITLE
new dark-green theme

### PR DESCRIPTION
**Pull request by Darkmagister**
### What does this PR do?

adding a new theme based on the default, predominantly green

### Motivation

i love green!

### Additional Notes

pictures of the theme:

[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[guitar-playingpng](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)
[](https://postimg.cc/gallery/N0BPm8w)

### CODE REVIEW

**Comment by twollgam** [comment]
Nice!

**Review by Baklap4 — COMMENTED** [review]
Haven't tested it, but the screenshots are looking good for a 2nd theme!
If @Lord-Kamina or @ooshlablu can test/approve i see nothing stopping this from merging!

**Comment by Lord-Kamina** [comment]
Not a fan of the (bright) green but this is the very definition of "up to taste". I'll try to test it today.

**Comment by Baklap4** [comment]
> Not a fan of the (bright) green but this is the very definition of "up to taste". I'll try to test it today.

Hmmm yeah that's the difference between taste. What we might can consider if we want to have this shipped with the main game or if it needs a couple of more tweaks before shipping it with the game. That's up for discussion here :)

I do like to see a 2nd theme ready to go with Performous, this _might_ encourage people to create their own themes and create a pr for them!

**Comment by Baklap4** [comment]
@Darkmagister I'm missing the green color pallete for the webserver interface. Are you able to include that within this PR? The changes needed are the css files in the `themes/green/www` directory

**Comment by Lord-Kamina** [comment]
> > Not a fan of the (bright) green but this is the very definition of "up to taste". I'll try to test it today.
> 
> 
> 
> Hmmm yeah that's the difference between taste. What we might can consider if we want to have this shipped with the main game or if it needs a couple of more tweaks before shipping it with the game. That's up for discussion here :)
> 
> 
> 
> I do like to see a 2nd theme ready to go with Performous, this _might_ encourage people to create their own themes and create a pr for them!

In that sense, what I'd like is maybe a somewhat darker shade of green; say, for example <span style="background-color:#228B22;text:black">forestgreen</span>

**Comment by Darkmagister** [comment]
> @Darkmagister I'm missing the green color pallete for the webserver interface. Are you able to include that within this PR? The changes needed are the css files in the `themes/green/www` directory

i'll check to make a theme for the webpage

**Comment by Darkmagister** [comment]
> > > Not a fan of the (bright) green but this is the very definition of "up to taste". I'll try to test it today.
> > 
> > 
> > Hmmm yeah that's the difference between taste. What we might can consider if we want to have this shipped with the main game or if it needs a couple of more tweaks before shipping it with the game. That's up for discussion here :)
> > I do like to see a 2nd theme ready to go with Performous, this _might_ encourage people to create their own themes and create a pr for them!
> 
> In that sense, what I'd like is maybe a somewhat darker shade of green; say, for example forestgreen/#228B22

i really like the bright green and dark border/background ... a more darker green i think it's more difficult to see on a dark background.

**Comment by Lord-Kamina** [comment]
> 

Like I said, matter of opinion.

Could you humor me and make some screens with a slightly darker shade? (not necessarily the same one I gave before); no need to commit it, just to see how it looks?

**Comment by Darkmagister** [comment]
> > 
> 
> Like I said, matter of opinion.
> 
> Could you humor me and make some screens with a slightly darker shade? (not necessarily the same one I gave before); no need to commit it, just to see how it looks?

i've tried to convert only the bright green to the forestgreen (not the green in the bottom) and this is the result

[Screenshot green](https://postimg.cc/gallery/6KjXZ6M)
(hope it's enough)

**Comment by ooshlablu** [comment]
Tested with vocals + guitar on Ubuntu 20.04 with the deb and appimage. Gameplay looks good to me, no issues introduced AFAICT. There looks good as well, but I don't think it should be the default theme. @Darkmagister if you could, please set it this to be a secondary theme, and update the branch to pull in some of the other PR's that have been merged. Will give it another go when the packages are ready for that.

**Comment by Baklap4** [comment]
>  @Darkmagister if you could, please set it this to be a secondary theme, and update the branch to pull in some of the other PR's that have been merged

@ooshlablu the theme is saved into your local `config.xml` file. This way once you've set the theme Performous remembers this and loads it when the application restarts.

The default theme is still the default upon removing that line from the `config.xml` if i'm correct (please verify). If that's the case this can get merged

**Review by Baklap4 — APPROVED** [review]
LGTM, a dark-green theme has been added and works alright.
There is a problem (but not introduced in this PR) where setting another theme within the settings menu doesn't refresh the theme at runtime. You have to manually shutdown and restart performous. I'll make a new issue for that.

**Comment by Baklap4** [comment]
Added #819 for the above problem/enhancement

**Pull request merged**
