### PR TITLE
add note type 'R' (rap) and 'G' (golden?)

### PR DESCRIPTION
**Pull request by nieknooijens**
So I was adding some more songs today and I got a file for this new BTS song (dynamite - see attachment) 
[BTS - Dynamite.txt](https://github.com/performous/performous/files/5212988/BTS.-.Dynamite.txt)

and it contained 2 new types of notes: 'R' (RAP) and 'G' (probably Golden).
for now I made R the same as freestyle since older songs used to do this, meaning that it does count score (1x), however in guitar hero "rap" notes dont count against your score. 
I can change that, but that means it needs a new graphic.

I made 'G' notes behave the same as '*' (golden) notes for now, don't know why they were introduced.
Anyhow, here's a hotfix so the song loads correctly without an "unknown note type" error.

### CODE REVIEW

**Comment by Lord-Kamina** [comment]
LGTM. If you want to look further into it though, I found the PR where these were originally added to USDX, https://github.com/UltraStar-Deluxe/USDX/pull/210

**Review by Lord-Kamina — DISMISSED** [review]

**Comment by nieknooijens** [comment]
oh OSX generate app bundle failed

**Comment by nieknooijens** [comment]
rebased on master, check should succeed now

**Review by Baklap4 — APPROVED** [review]
When CI succeeds feel free to merge 👍

**Pull request merged**
