### PR TITLE
Sing with 8 different microphones

### PR DESCRIPTION
**Pull request by Baklap4**
Changed the layout a bit so all the microphones fit in the window
Added a few colors to match the microphones
Made it possible to sing with all the 8 microphones

### CODE REVIEW

**Comment by nieknooijens** [comment]
I'll test this tomorrow morning, thanks for helping out to make performous better!

**Comment by Baklap4** [comment]
Alright let me know if something broken :P Thanks :)

**Comment by nieknooijens** [comment]
So I hooked up my xenyx x2442 and used the direct-outputs to get per-microphone input on the pc.
I can't find any bug in particular, even the duets work just fine:
schermafdruk van 2015-02-23 11 05 45
schermafdruk van 2015-02-23 11 06 02

**Comment by Baklap4** [comment]
Awesome glad i did something useful thanks a lot :+1:

**Pull request merged**
