### PR TITLE
Locale fix

### LINKED ISSUE #435: LANG envvar should be used to determine language, not LC_CTYPE
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to run performous in my non-default locale (`sk_SK.utf8`).

### What did you expect to see?

Common way to switch program language on Linux is by setting `LANG` environment variable, e. g. `LANG=fr_FR.utf8 mc` starts Midnight commander in French. For some reason performous reads `LC_CTYPE` instead, so while `LANG="fr_FR.utf8" performous` does not switch the language to French, `LC_CTYPE="fr_FR.utf8" performous` does. `LANG` should be honoured as this is a standard.

### What did you see instead?
Looks like performous only checks for `LC_CTYPE` and ignores the rest of `LC_` variables or `LANG`.

### Output of `performous --version`:

```
Performous 1.1-766-gc4fcfecc
```

### What is your environment & configuration (arguments, platform, ...)?

Arch Linux 64bit

### PR DESCRIPTION
**Pull request by Baklap4**
Fixes to use the current locale.

### Closes Issue(s)

* Closes #435

### CODE REVIEW

**Comment by Lord-Kamina** [comment]
@jose1711 Can you check whether this branch behaves as you'd expect it to?

**Comment by Baklap4** [comment]
@Lord-Kamina as #435 is closed do we still need this? It'd be nice to pick the current system default

**Comment by Lord-Kamina** [comment]
Yes we do need this still. Despite the fact @jose1711's issue was caused by that script and not really understanding what LANG does, our code is sort-of broken as illustrated by my comments earlier comparing both versions.

**Comment by Baklap4** [comment]
Alright let me update it so it can be merged :+1:

**Pull request merged**
