### PR TITLE
added autocompletion with max 5 autocompletions

### PR DESCRIPTION
**Pull request by Baklap4**
Added autocompletion on page 3.
Max 5 autocompletions.

### CODE REVIEW

**Comment by Baklap4** [comment]
Build failed because the buildserver doesn't have cpp-netlib installed as the wiki says: https://github.com/performous/performous/wiki/Building-and-installing-from-source#Debian_and_Ubuntu: 
"Note: when building the webserver-branch you need CPP-netlib get the latest version from:http://cpp-netlib.org/ and unpack the folder named "boost" into /usr/include. if done correctly you should have the file: /usr/include/boost/network/protocol/http/server.hpp among some others."

**Comment by Baklap4** [comment]
I didn't get anything slow even with 4000 songs in my library (copied my library twice). But i'll create a new entry for it :+1:

**Comment by nieknooijens** [comment]
I did some testing and most of the time it works allright, but when I search for "invoke" this happens:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc7ffd700 (LWP 7160)]
shared_count (r=..., this=0x7fffc7ffc018)
    at /usr/include/boost/smart_ptr/detail/shared_count.hpp:382
382	        if( pi_ != 0 ) pi_->add_ref_copy();
(gdb) bt
#0  shared_count (r=..., this=0x7fffc7ffc018)
    at /usr/include/boost/smart_ptr/detail/shared_count.hpp:382
#1  shared_ptr (r=..., this=0x7fffc7ffc010)
    at /usr/include/boost/smart_ptr/shared_ptr.hpp:397
#2  operator[] (pos=<optimized out>, this=0x7fffffffd840)
    at /home/niek/Projects/performous/game/songs.hh:27
#3  WebServer::POSTresponse (this=0x7fffffffd6b0, request=...)
    at /home/niek/Projects/performous/game/webserver.cc:148
#4  0x0000000000571f5b in WebServer::handler::operator() (this=0x7fffc7ffca20, 
    request=..., response=...)
    at /home/niek/Projects/performous/game/webserver.cc:16
#5  0x0000000000577e82 in boost::network::http::sync_connection<boost::network::http::tags::http_server, WebServer::handler>::handle_read_headers (
    this=0x7fffb40034d0, ec=..., bytes_transferred=140736548815536)
    at /usr/include/boost/network/protocol/http/server/sync_connection.hpp:153
#6  0x0000000000578ca1 in call<boost::shared_ptr<boost::network::http::sync_connection<boost::network::http::tags::http_server, WebServer::handler> >, boost::system::error_code const, unsigned long> (b2=<synthetic pointer>, b1=..., u=..., 
    this=0x7fffc7ffc530) at /usr/include/boost/bind/mem_fn_template.hpp:271
#7  operator()<boost::shared_ptr<boost::network::http::sync_connection<boost::network::http::tags::http_server, WebServer::handler> > > (a2=<optimized out>, 
    a1=..., u=..., this=0x7fffc7ffc530)
    at /usr/include/boost/bind/mem_fn_template.hpp:286

this is a threading problem ;-(
also when I click on an autocomplete entry it is searched, but performous can't handle both artist and title data so you'll end up with empty search results, better would be to just add that song to the list.

**Comment by Baklap4** [comment]
The threading problem is not occured by me as it wss and still is in the most recent version of the webserver branch

**Comment by Baklap4** [comment]
How do you mean you'll end up with empty results?
When i'm searching and click an entry it is filled in in the search textbox. And the result come back:

image

image

There's a problem with special characters though. When i'm looking for Metallica - Welcome Home (Sanitarium) the moment i type ( it can't find anything anymore.. will dive into this

**Comment by nieknooijens** [comment]
I'll have this on hold for a few weeks since animecon is tomorrow and in 2 weeks I go to Japan.
after that I'll look into this once more.

**Comment by Baklap4** [comment]
Alright :)
Have fun @ animecon and Japan!

**Pull request merged**
