### PR TITLE
Audio: Set aubio parameters inside Audio::Impl

### LINKED ISSUE #525: Fix nullreference caused by aubio on windows
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Running performous on windows results into a nullreference

#### stacktrace

```
libaubio-5.dll!aubio_tempo_set_silence(_aubio_tempo_t * o=0x0000000000000000, float silence) Line 147
	at ../src/tempo\tempo.c(147)
Performous.exe!Audio::Audio() Line 556
	at C:\Users\aspeiard\Desktop\Persoonlijk\performous-win\game\audio.cc(556)
Performous.exe!mainLoop(const std::string & songlist={...}) Line 130
	at C:\Users\aspeiard\Desktop\Persoonlijk\performous-win\game\main.cc(130)
Performous.exe!SDL_main(int argc=1, char * * argv=0x000001f79f640000) Line 394
	at C:\Users\aspeiard\Desktop\Persoonlijk\performous-win\game\main.cc(394)
Performous.exe!main_getcmdline(...) Line 177
	at C:\Users\aspeiard\Desktop\Persoonlijk\vcpkg-performous\buildtrees\sdl2\src\ase-2.0.10-149e8ce27e\src\main\windows\SDL_windows_main.c(177)
Performous.exe!invoke_main() Line 107
	at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(107)
Performous.exe!__scrt_common_main_seh() Line 288
	at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288)
Performous.exe!__scrt_common_main() Line 331
	at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(331)
Performous.exe!WinMainCRTStartup() Line 17
	at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp(17)
kernel32.dll!00007fff66307bd4()
ntdll.dll!00007fff680aced1()
```

this is due to `aubio_win_size` and `aubio_hop_size` being changed from 2048 and 1024 to  1536 and 768. The function where these values are used is [`new_aubio_tempo`](https://aubio.org/doc/0.4.0/tempo_8h.html#aaa49f5d6554904a452d031775f385521)

### What did you expect to see?

a running and working performous.

### What did you see instead?

A nullreference

### Output of `performous --version`: (_What version of Performous are you using?_)

latest master

### What is your environment & configuration (arguments, platform, ...)?

Windows 10, packages from vcpkg.

### PR DESCRIPTION
**Pull request by Lord-Kamina**
### What does this PR do?

Initial naive try to fix #525 

I have a feeling I'll need to take a dive into the aubio source; but, before I do: @Baklap4 could you please check if this corrects the issue?

### More

- [ ] Added/updated documentation

### CODE REVIEW

**Comment by Baklap4** [comment]
Will give it a try :)

**Comment by Baklap4** [comment]
Alright my windows machine is working again.. gonna try this out later today or tomorrow

**Comment by Baklap4** [comment]
Sadly this does not work with latest aubio (0.4.9)

**Comment by Baklap4** [comment]
@Lord-Kamina is this still needed with latest master (current state of windows build can be neglected)

**Comment by Lord-Kamina** [comment]
> @Lord-Kamina is this still needed with latest master (current state of windows build can be neglected)

No, I don't think so.

**Comment by Baklap4** [comment]
Closing this for now. since OP said it's probably not needed. We can always reopen if it needs to.

**Pull request closed without merging**
