### PR TITLE
Fix - Game feedback should be localized

### LINKED ISSUE #423: game feedback should be localised too
https://github.com/performous/performous/blob/fb64ebc17c08fd3d0b454cd0592e93bd6ab79f0f/game/layout_singer.cc#L72

performous already is l10n friendly so i think it should be also extended to the feedback game provides during singing/playing/dancing.

### PR DESCRIPTION
**Pull request by Baklap4**
### What does this PR do?
Some game feedback didn't get translated. With this PR it's fixed.

### Closes Issue(s)
* Closes #423 

### Motivation
@jose1711 mentioned some game feedback didn't get localized

### CODE REVIEW

**Comment by Baklap4** [comment]
@jose1711 can you check if this pr fixes this localization thing :o?

**Comment by jose1711** [comment]
@Baklap4 tested with an updated gettext file and it works nicely. thank you!

**Comment by Baklap4** [comment]
@jose1711 Once this branch is pushed, feel free to create a pr for your updated translation files ^..^!

**Comment by Baklap4** [comment]
@Lord-Kamina / @nieknooijens updated branch so it can be merged to master.

**Pull request merged**
