### PR TITLE
Fix build with ffmpeg-5.x.x

### PR DESCRIPTION
**Pull request by sergiomb2**
### Motivation

Fix build with new ffpmeg 5.x.x , seems more trivial 

please test it 

find the solution here https://github.com/dmlc/decord/pull/160/files when I was searching by 

error: invalid conversion from 'AVCodec**' to 'const AVCodec**' [-fpermissive] or initializing argument 5 of int av_find_best_stream

### CODE REVIEW

**Comment by Baklap4** [comment]
Might be nice to add this on top of the current ffmpeg 4 support in the same way this has been done for libxml++2.6 - libxml++5.0.0

**Comment by OznOg** [comment]
if ffmpeg start to use "const", the end is near, brace yourself, winter is coming

**Comment by OznOg** [comment]
```
diff --git a/game/ffmpeg.cc b/game/ffmpeg.cc
index 5005ed5a..196a6585 100644
--- a/game/ffmpeg.cc
+++ b/game/ffmpeg.cc
@@ -236,6 +236,17 @@ class FFmpeg::Error: public std::runtime_error {
        }
 };
 
+template<std::size_t pos, class F>
+struct ArgTypeAt;
+
+template<std::size_t pos, class R, class... Args>
+struct ArgTypeAt<pos, R(Args...)> {
+    using type = decltype(std::get<pos>(std::tuple<Args...>()));
+};
+
+template<std::size_t pos, class F>
+using ArgTypeAt_t = std::remove_reference_t<typename ArgTypeAt<pos, F>::type>;
+
 FFmpeg::FFmpeg(fs::path const& _filename, int mediaType) : m_filename(_filename) {
        static std::once_flag static_infos;
        std::call_once(static_infos, &printFFmpegInfo);
@@ -251,7 +262,7 @@ FFmpeg::FFmpeg(fs::path const& _filename, int mediaType) : m_filename(_filename)
        if (err < 0) throw Error(*this, err);
        m_formatContext->flags |= AVFMT_FLAG_GENPTS;
        // Find a track and open the codec
-       AVCodec* codec = nullptr;
+       std::remove_pointer_t<ArgTypeAt_t<4, decltype(av_find_best_stream)>>  codec = nullptr;
        m_streamId = av_find_best_stream(m_formatContext.get(), static_cast<AVMediaType>(mediaType), -1, -1, &codec, 0);
        if (m_streamId < 0) throw Error(*this, m_streamId);
 
```
for the record, some voodoo guess on the function argument that should compile in both versions.... not sure I wan to see that commited anyway :)

**Comment by sergiomb2** [comment]
BTW , I not an authority in how to fix ffmpeg, anyway I found this PR https://github.com/acoustid/chromaprint/pull/108/files that can help you

**Comment by OznOg** [comment]
> BTW , I not an authority in how to fix ffmpeg, anyway I found this PR https://github.com/acoustid/chromaprint/pull/108/files that can help you

Yes the fixes are quite straight forward, but we would really need to have a local build not to patch things randomly

**Comment by Baklap4** [comment]
Converted to Draft since workflows do fail and outdated

**Comment by ooshlablu** [comment]
It looks like this will be a problem in Fedora 36: https://github.com/performous/performous-docker/pull/16

**Comment by OznOg** [comment]
will be fixed in #752

**Pull request closed without merging**
