### PR TITLE
remove unused variable to allow compilation on macos

### PR DESCRIPTION
**Pull request by taynaron**
### What does this PR do?

remove an unused var to allow performous to compile on arm64 mac builds using the performous-app-build.sh script.

### Motivation

To compile performous

### More

- [ ] Added/updated documentation

### CODE REVIEW

**Review by Baklap4 — CHANGES_REQUESTED** [review]
Looks like this is missed... thanks for noticing!
@ooshlablu since this is the guitar bit of performous can you give this a try?

Not quite sure why this was left in or does it still need some tweaks? (there are a lot of fixme's regarding polyphony in this file)

@taynaron please remove the comment so it gets actually deleted

**Comment by taynaron** [comment]
comment removed, ready for review

**Comment by ooshlablu** [comment]
@taynaron @Baklap4 FWIW I tested singing and guitar/bass on Ubuntu and it seems fine there. I do want to test drums before I give it the +1, I'm hoping to get some time this weekend to rope in the family to do so :-)

**Comment by Baklap4** [comment]
Code looks fine, so when you're ready to give it +1 we can merge it :)

**Review by Baklap4 — APPROVED** [review]

**Pull request merged**
