### PR TITLE
Prepare for AppImage requirements

### PR DESCRIPTION
**Pull request by deuteragenie**
- Add an initial AppImageBuilder file which will be used to generate the AppImage.  It has been tested on several Ubunutu versions and the resulting AppImages have been linted successfully for compatibility with many distros.

- Reorder the .desktop file items in accordance with the Freedesktop specs, review keywords. The file has also been validated with the freedesktop dedicated tool.

- Add a set of fixed icons based on the .svg, as .svg is not required to be supported by all distros, according to the freedesktop specs.  These icons will be installed at the correct location in the revised build scripts.  They can be used depending on context (browser, sidebars, menus etc.) by the OS.

### CODE REVIEW

**Comment by Baklap4** [comment]
Can you create a little tutorial on how to use this within this PR and / or maybe wiki?

**Comment by deuteragenie** [comment]
I'll update the wiki.

**Comment by deuteragenie** [comment]
I described how to build the AppImage here:

https://github.com/performous/performous/wiki/Building-and-installing-from-source#Building_an_AppImage_Experimental

**Comment by Baklap4** [comment]
Currently fails. Waiting for #627 then this can work

**Comment by deuteragenie** [comment]
> Currently fails. Waiting for #627 to merge then this can work

How could this PR fail if it is only adding a few files that will be required later on if/when AppImage will be build ?

**Comment by Baklap4** [comment]
@ooshlablu can you extend on this and add this AppImage as one of the artifacts to our current workflows in gh-actions?

**Comment by Baklap4** [comment]
Closing this in favor of #736

**Pull request closed without merging**
