### PR TITLE
Re-Design Web UI (performous+)

### PR DESCRIPTION
**Pull request by marwin89**
### What does this PR do?

- Re-Design of performous browser app for performous+ theme #920 
- Removing redundant files from performous+ theme (fonts, textures)
- See Screenshots below
- Some fixes for notes and lyrics font

### Closes Issue(s)

- #936 
- #937 

### Motivation

- Improve user experience for performous browser app

### More
New WebUI Design (for performous+ theme folder)
web-ui-desktop1
web-ui-mobile1

Old WebUI Design (default theme folder)
performous-web-ui

### Additional Notes

Testet in firefox and edge, desktop and mobile

### CODE REVIEW

**Comment by ooshlablu** [comment]
I tested the WebUI and everything looks good. I was able to add songs to a playlist, manipulate the playlist, search, and do everything else expected. :+1:

**Review by Baklap4 — COMMENTED** [review]
I'm wondering if the website folder is also smart in a way that if a html isn't there in a theme will it look for the fallback one in the default theme? if yes then we don't need to duplicate most of the js, html, images and css. Can this be checked before we merge it ?

**Comment by marwin89** [comment]
> I'm wondering if the website folder is also smart in a way that if a html isn't there in a theme will it look for the fallback one in the default theme? if yes then we don't need to duplicate most of the js, html, images and css. Can this be checked before we merge it ?

It works and looks for a fallback. I tested it. We can remove
- all the js,
- all the fonts,
- all the css (except style.css),
- all the images (except Logo.png).

to avoid duplicates. But we need to keep html files cause I changed every html file a bit.

**Review by Baklap4 — DISMISSED** [review]
LGTM

**Comment by Baklap4** [comment]
@twollgam are the 2 linked issues also resolved by this :)?

**Comment by twollgam** [comment]
@Baklap4 

#937 is fixed 👍
#936 is fixed but not optimal. Now the notes are visible but they are not so eye catching and I cannot read the "freestyle". Maybe good enough for a merge, not good enough to close the issue.

**Comment by marwin89** [comment]
@Baklap4 : I made the freestyle notes more visible (commit 5), @twollgam  agreed on that. Please merge.

**Comment by marwin89** [comment]
@Baklap4 : add Background Gradient for WebUI (Commit 6)
web-ui-background-gradient
web-ui-background-gradient-desktop

**Review by Baklap4 — APPROVED** [review]

**Pull request merged**
