### PR TITLE
Added performous/performous-mxe as submodule to performous.

### LINKED ISSUE #253: Git submodule performous/performous-mxe
Within the win32 folder of performous/performous we have an mxe folder with some files to make mxe and build performous for windows on linux/macos. This is all great, however these files shouldn't be maintained here but within the performous/mxe repo. With Git Submoduling we can easily use the performous/performous-mxe repo and have all mxe related stuff there.

Any objections? @performous/contributors

### PR DESCRIPTION
**Pull request by Baklap4**
* Adds https://github.com/performous/performous-mxe to the main repo as submodule.
* Removes files which were not used anymore + moved make-installer.py to win32 folder.
* Add -DEPOXY_SHARED to succeed building for windows using mxe
* Submodule will be in this directory: /win32/performous-mxe

# Referenced issue:
* Closes #253 
* https://github.com/performous/performous-mxe/pull/1

### CODE REVIEW

**Comment by Baklap4** [comment]
Discuss, some like submodules, some hate them. I thought this was the 'cleanest' way to go to split mxe/windows build related stuff from here. @performous/contributors

**Comment by nieknooijens** [comment]
why performous-MXE? it's pretty old and I usually use the "official" MXE since that one supports dynamic builds.

**Comment by Baklap4** [comment]
@nieknooijens the script uses the master branch of mxe. Since we had this repo it's better to just shove all the mxe related stuff, like creating a windows release to there

**Comment by Baklap4** [comment]
@Lord-Kamina will look at this tonight. Haven't been too active lately due to events sadly. Aside from this anything else or just ready to go then? I'd love to make it submodule since it makes building way easier....

**Comment by Baklap4** [comment]
@nieknooijens The idea behind this was this repo is set up using submodules. The tools to build on windows in my opinion then moved to the performous/performous-mxe repo to provide 1 script to build a release for windows using the local cloned repo. However these files have been reverted due to discussion it should only contain mxe related stuff. That's alright with me but i've asked multiple times on how to build local instead of master or a specific tag, however none failed to answere me keeping me to a deadend. @TobiX said the two scripts on performous-mxe should be enough to build the specific tag and the daily master branch. But HOW do you build the master branch then for example ? Locally the files have been reverted to here.. keeping only one file: make-release.sh

**Comment by nieknooijens** [comment]
@Baklap4 well as long as there is at least one automated script that works it's ok with me.

**Comment by Baklap4** [comment]
@nieknooijens will look into it this week somewhere

**Comment by Baklap4** [comment]
Closing this since a lot of stuff had happened since.

**Pull request closed without merging**
