### PR TITLE
ffmpeg -- oh how I hate you.

### PR DESCRIPTION
**Pull request by Lord-Kamina**
### What does this PR do?

Hopefully eventually fix ffmpeg somewhat, but most likely will end-up as nothing, given I have zero experience with ffmpeg.

That said... it seems the macos build is failing because we're using a _newer_ api...?

### More

- [ ] Added/updated documentation

### CODE REVIEW

**Comment by Lord-Kamina** [comment]
This _should_ be working now?

**Review by Baklap4 — COMMENTED** [review]
Code looks fine, haven't run it though...
Also would it be possible to include a change to the windows.yml?
Basicly update the commit sha to '2f210a9c13fcf2b0c36b1f2187366feec37e3390' or above (as this failed the ffmpeg stuff too, so we can check if this also still work on windows?

**Comment by Lord-Kamina** [comment]
> Code looks fine, haven't run it though... Also would it be possible to include a change to the windows.yml? Basicly update the commit sha to '2f210a9c13fcf2b0c36b1f2187366feec37e3390' or above (as this failed the ffmpeg stuff too, so we can check if this also still work on windows?

Can you change that? It should be possible for you to commit directly to the branch...

I ran it and got to the main menu and the bg music seemed fine to me at least.

**Comment by Baklap4** [comment]
@Lord-Kamina updated the branch to contain latest vcpkg code. Build seems to work and ran a couple of songs didn't find something not working :)

**Review by Baklap4 — APPROVED** [review]

**Review by ooshlablu — APPROVED** [review]
@Lord-Kamina @Baklap4 I did a sing test with the AppImage and deb on Ubuntu 24.04 and it looks good from that perspective. I tested songs with different formats under the hood, like ogg and mp3, and everything seems to work as expected. I will hopefully get a test with the instruments in a little bit, but I'm not really expecting any issue there since it seems like nothing in that code path got changed.

**Pull request merged**
