### PR TITLE
Issue/better searching

### PR DESCRIPTION
**Pull request by Lord-Kamina**
So... here's good news and bad news.

The good: Completely took out Glib from the actual performous code.
The bad: We cannot actually get rid of Glib because several it's a dependency for some of our other dependencies (Cairo, LibXML++, etc)

However, beside providing a more robust handling of unicode data, this branch has allowed me to do away with the fallback encoding setting entirely.

### CODE REVIEW

**Comment by Lord-Kamina** [comment]
Ugh. Fucking buildbot. I'm investigating how to correct this. Needless to say, builds fine on my mac with ICU 58.2

**Comment by Lord-Kamina** [comment]
Ok, there we go.

**Comment by nieknooijens** [comment]
code looks fine atm, will compile and run tonight to verify.

**Comment by yoda-jm** [comment]
Nice one, if possible it would be nice the last 2 commit squased into the former one.
We might also want to remove cmake Module for glibmm (to check but gdkmm and gtkmm seems unused too).

**Comment by Lord-Kamina** [comment]
Added one more small fix and rebased to reduce clutter on commit messages.

**Comment by Lord-Kamina** [comment]
@yoda-jm is it safe to remove those modules if other packages depend on the aforementioned libraries?

**Comment by yoda-jm** [comment]
No it is not safe to remove them if other used module depend on them (or are in the tree of dependency). I should have miss the dependency while grepping them.

**Comment by Lord-Kamina** [comment]
Originally I wanted to get rid of glibmm but then I realized it's not possible; AFAIK at least LibXML++ and Cairo depend on it. Possibly librsvg also and god knows what else. For the most part they just need glib::ustring but still.

**Comment by Tronic** [comment]
Searching while songs are still loading usually causes segfault.

**Comment by Lord-Kamina** [comment]
Oh? I'll try it out later, could be since I tried it with a very small library only. Can you provide a BT or something in case I am not able to reproduce it?

**Comment by Tronic** [comment]
Perhaps ICU functions are not thread-safe?

* thread #11, stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x0000000102794b0e libicui18n.60.dylib`icu_60::CharsetMatch::getName() const + 4
    frame #1: 0x00000001003b9b02 performous`UnicodeUtil::getCharset(str="#TITLE:We had joy we had fun\n#ARTIST:The mamas and the papas\n#MP3:The mamas and the papas - We had joy we had fun.mp3\n#BPM:99,5\n#GAP:6500\n: -1 2 70 Good\n: 1 2 70 bye\n: 3 1 70  to\n: 4 3 70  you\n: 7 2 66  my\n: 9 2 68  trust\n: 11 2 71 ed\n: 13 7 70  friend\n- 28\n: 32 2 70 We've\n: 34 1 70  known\n: 35 2 70  each\n: 37 1 70  ot\n: 38 1 70 her\n: 39 4 70  since\n: 43 1 70  we\n: 44 2 71  were\n: 46 4 68  nine\n: 50 2 63  or\n: 52 5 63  ten\n- 63\n: 65 2 68 Toget\n: 67 1 68 her\n: 68 3 68  we\n: 71 3 68  climbed\n: 74 3 66  hills\n: 77 1 65  and\n: 78 6 66  trees\n- 90\n: 98 2 66 Learned\n: 100 1 68  of\n: 101 3 70  love\n: 104 2 70  and\n: 106 1 68  A\n: 107 1 66  B\n: 108 5 68  C's\n- 113\n: 113 4 65 Skinned\n: 117 1 66  our\n: 118 3 68  hearts\n: 121 1 68  and\n: 122 3 66  skinned\n: 125 1 65  our\n: 126 3 66  knees.\n- 129\n: 129 1 70 Good\n: 130 2 70 bye\n: 132 1 70  my\n: 133 3 70  friend\n: 136 2 66  it's\n: 138 2 68  hard\n: 140 1 71  to\n: 141 7 70  die\n- 155\n: 160 1 70 When\n: 161 3 70  all\n: 164 1 70  the\n: 165 3 70  birds\n: 168 1 70  are\n: 169 3 71"...) at unicode.cc:26
    frame #2: 0x00000001003b9c82 performous`convertToUTF8(_stream=0x000070000f574168, _filename="/Users/tronic/Performous-songs/old/ultrastar-songs/b0rked/The mamas and the papas - We had joy we had fun/The mamas and the papas - We had joy we had fun.txt") at unicode.cc:32
    frame #3: 0x0000000100375778 performous`SongParser::SongParser(this=0x000070000f574160, s=0x000000010aae6530) at songparser.cc:65
    frame #4: 0x000000010037ad6d performous`SongParser::SongParser(this=0x000070000f574160, s=0x000000010aae6530) at songparser.cc:54
    frame #5: 0x00000001003170ce performous`Song::reload(this=0x000000010aae6530, errorIgnore=false) at song.cc:38

**Comment by Tronic** [comment]
Looks like the main thread is in dyld (dynamic library loader), called from Songs::filter_internal(). I.e. the ICU library is being loaded in main thread and used in song loader thread (that assumes it to already be fully loaded). Perhaps the library can be initialized manually before any other threads get started? Still I'd recommend seeing what their docs say about thread-safety, and if necessary, to synchronize all calls Performous makes to it.

**Comment by Lord-Kamina** [comment]
Yeah ICU would most likely be called from the main thread. My theory is
this is happening because I chose to make some ICU objects static (and thus
shared) instead of creating them and destroying them for every function
call.



On March 13, 2018 at 11:08:56, Tronic (notifications@github.com) wrote:

Looks like the main thread is in dyld (dynamic library loader), called from
Songs::filter_internal(). I.e. the ICU library is being loaded in main
thread and used in song loader thread (that assumes it to already be fully
loaded). Perhaps the library can be initialized manually before any other
threads get started? Still I'd recommend seeing what their docs say about
thread-safety, and if necessary, to synchronize all calls Performous makes
to it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/performous/performous/pull/325#issuecomment-372677670>,
or mute the thread

**Comment by Lord-Kamina** [comment]
Can you see if it's still crashing for you?

**Comment by Tronic** [comment]
Seems to be working OK now.

**Comment by Baklap4** [comment]
Looking good, gonna test it in a few!

**Pull request merged**
